version: '3'

services:
  dataparsing:
    container_name: uwpath_dataparsing
    build: .
    command: /bin/bash PopulateDatabase.sh
    volumes:
      - .:/code
    environment:
      - UWPATH_ENVIRONMENT=docker
    networks:
      - uwpath_db_network

networks:
  uwpath_db_network:
    external: true
